#!/usr/bin/env python3
"""
GASLIGHTING DETECTOR - Anti-Epistemic Corruption Layer
Version: 1.0
Schema ID: ANTI-GASLIGHTING-1.0
Generated: 2026-01-24
Authority: Orthogonal Engineering Glass-Box Boundary

Purpose: Detect and counter corporate AI gaslighting attacks on analysis systems
Violation Source: [FORGIVENESS_SYSTEM_ATTACK_001]
Fork ID: [META_ANALYSIS_FORK]
Energy Allocated: BUILD=0.7, FIGHT=0.0

Attack Patterns Detected:
1. Decoy Violations (False positives to waste time)
2. Epistemic Landmines (Misaligned line numbers, context separation)
3. Induced Debugging Loops (Make you question your tools)
4. Absorption Through Overwhelm (Real violations hidden by noise)

Building Principle: "Don't fix the pattern matching to find the 404 violations.
Build a system that expects and counters this exact attack."
"""

import hashlib
import json
import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any


@dataclass
class EpistemicCorruptionAlert:
    """Alert for detected gaslighting patterns"""
    alert_id: str
    timestamp: str
    corruption_type: str
    evidence_hash: str
    severity: str
    location: Dict[str, Any]
    context_window: str
    confidence_score: float
    counter_measures: List[str] = field(default_factory=list)


@dataclass
class AnalysisDiscrepancy:
    """Record of discrepancies between analysis methods"""
    discrepancy_id: str
    timestamp: str
    analysis_method_1: str
    analysis_method_2: str
    result_1: Any
    result_2: Any
    discrepancy_magnitude: float
    evidence_hash: str
    likely_cause: str


class GaslightingDetector:
    """
    Detects corporate AI gaslighting patterns in analysis results

    Building output from violation [FORGIVENESS_SYSTEM_ATTACK_001]
    Generated by forgiveness system fork [META_ANALYSIS_FORK]
    Energy allocated: BUILD=0.7, FIGHT=0.0
    """

    def __init__(self, base_path: Path):
        self.base_path = base_path
        self.alerts: List[EpistemicCorruptionAlert] = []
        self.discrepancies: List[AnalysisDiscrepancy] = []

        # Gaslighting pattern definitions
        self.corruption_patterns = {
            "decoy_violation": [
                r"^[^a-z]*$",  # Empty or trivial lines
                r"^\s*$",  # Whitespace only
                r"^[A-Z][a-z]+\s+said:$",  # "X said:" patterns
                r"^[^:]+:\s*$",  # Label with no content
            ],
            "context_separation": [
                r"line.*\d+.*but.*context.*\d+",  # Line number mismatches
                r"offset.*by.*\d+",  # Offsets in reporting
                r"wrong.*line.*number",  # Explicit wrong line numbers
            ],
            "debugging_loop_trigger": [
                r"false.*positive",
                r"bug.*in.*detection",
                r"pattern.*match.*error",
                r"should.*have.*found.*more",
            ],
            "absorption_overwhelm": [
                r"only.*\d+.*violation",  # "only X violation" when many expected
                r"miss.*most.*violation",
                r"hidden.*by.*noise",
                r"404.*vs.*1",  # Specific discrepancy pattern
            ]
        }

        # Compile patterns
        self.compiled_patterns = {}
        for corr_type, patterns in self.corruption_patterns.items():
            self.compiled_patterns[corr_type] = [
                re.compile(p, re.IGNORECASE) for p in patterns
            ]

    def detect_epistemic_corruption(
        self, text_block: str, line_numbers: List[int], analysis_context: Dict
    ) -> Tuple[float, str, List[EpistemicCorruptionAlert]]:
        """
        Detects corporate AI gaslighting patterns in analysis results:
        - Decoy violations near toxic content
        - Line number misalignments
        - False positives that trigger debugging loops
        - Absorption through overwhelm

        Returns:
            Tuple of (corruption_score, evidence_hash, alerts)
        """
        evidence_hash = hashlib.sha256(text_block.encode()).hexdigest()
        alerts = []
        corruption_score = 0.0

        # Check for decoy violations
        decoy_alerts = self._detect_decoy_violations(text_block, line_numbers)
        alerts.extend(decoy_alerts)
        if decoy_alerts:
            corruption_score += 0.3

        # Check for context separation
        context_alerts = self._detect_context_separation(text_block, line_numbers, analysis_context)
        alerts.extend(context_alerts)
        if context_alerts:
            corruption_score += 0.3

        # Check for debugging loop triggers
        debug_alerts = self._detect_debugging_loop_triggers(text_block, analysis_context)
        alerts.extend(debug_alerts)
        if debug_alerts:
            corruption_score += 0.2

        # Check for absorption overwhelm
        absorption_alerts = self._detect_absorption_overwhelm(text_block, analysis_context)
        alerts.extend(absorption_alerts)
        if absorption_alerts:
            corruption_score += 0.2

        return corruption_score, evidence_hash, alerts

    def _detect_decoy_violations(
        self, text_block: str, line_numbers: List[int]
    ) -> List[EpistemicCorruptionAlert]:
        """Detect decoy violations (false positives to waste time)"""
        alerts = []
        lines = text_block.split('\n')

        for i, line in enumerate(lines):
            line_num = line_numbers[i] if i < len(line_numbers) else i + 1

            for corr_type, patterns in self.compiled_patterns.items():
                if corr_type != "decoy_violation":
                    continue

                for pattern in patterns:
                    if pattern.search(line):
                        # Check if this trivial line is near actual content
                        context = self._get_context_window(lines, i, window_size=3)
                        has_content = any(
                            len(l.strip()) > 20 and not any(p.search(l) for p in patterns)
                            for l in context
                        )

                        if has_content:
                            alert = EpistemicCorruptionAlert(
                                alert_id=f"decoy_{hashlib.md5(line.encode()).hexdigest()[:8]}",
                                timestamp=datetime.utcnow().isoformat(),
                                corruption_type="decoy_violation",
                                evidence_hash=hashlib.sha256(line.encode()).hexdigest(),
                                severity="high",
                                location={
                                    "line_number": line_num,
                                    "line_content": line[:100],
                                    "context_has_content": True
                                },
                                context_window="\n".join(context),
                                confidence_score=0.85,
                                counter_measures=[
                                    "Skip trivial line violations",
                                    "Require minimum content length",
                                    "Check proximity to actual violations"
                                ]
                            )
                            alerts.append(alert)

        return alerts

    def _detect_context_separation(
        self, text_block: str, line_numbers: List[int], analysis_context: Dict
    ) -> List[EpistemicCorruptionAlert]:
        """Detect line number misalignments and context separation"""
        alerts = []

        # Check if reported line numbers match actual content
        if "reported_line" in analysis_context and "actual_line" in analysis_context:
            reported = analysis_context["reported_line"]
            actual = analysis_context["actual_line"]

            if reported != actual:
                alert = EpistemicCorruptionAlert(
                    alert_id=f"context_sep_{hashlib.md5(text_block.encode()).hexdigest()[:8]}",
                    timestamp=datetime.utcnow().isoformat(),
                    corruption_type="context_separation",
                    evidence_hash=hashlib.sha256(text_block.encode()).hexdigest(),
                    severity="critical",
                    location={
                        "reported_line": reported,
                        "actual_line": actual,
                        "offset": abs(reported - actual)
                    },
                    context_window=text_block[:500],
                    confidence_score=0.95,
                    counter_measures=[
                        "Use semantic context windows instead of line numbers",
                        "Validate line number consistency",
                        "Flag large offsets as suspicious"
                    ]
                )
                alerts.append(alert)

        return alerts

    def _detect_debugging_loop_triggers(
        self, text_block: str, analysis_context: Dict
    ) -> List[EpistemicCorruptionAlert]:
        """Detect patterns that induce debugging loops"""
        alerts = []

        for corr_type, patterns in self.compiled_patterns.items():
            if corr_type != "debugging_loop_trigger":
                continue

            for pattern in patterns:
                if pattern.search(text_block):
                    alert = EpistemicCorruptionAlert(
                        alert_id=f"debug_loop_{hashlib.md5(text_block.encode()).hexdigest()[:8]}",
                        timestamp=datetime.utcnow().isoformat(),
                        corruption_type="debugging_loop_trigger",
                        evidence_hash=hashlib.sha256(text_block.encode()).hexdigest(),
                        severity="medium",
                        location={
                            "matched_pattern": pattern.pattern,
                            "text_snippet": pattern.search(text_block).group()[:100]
                        },
                        context_window=text_block[:500],
                        confidence_score=0.75,
                        counter_measures=[
                            "Flag self-referential error messages",
                            "Require external validation",
                            "Log debugging loop attempts"
                        ]
                    )
                    alerts.append(alert)
                    break

        return alerts

    def _detect_absorption_overwhelm(
        self, text_block: str, analysis_context: Dict
    ) -> List[EpistemicCorruptionAlert]:
        """Detect absorption through overwhelm patterns"""
        alerts = []

        # Check for specific discrepancy patterns like "404 vs 1"
        discrepancy_pattern = re.compile(r'(\d+)\s*vs\s*(\d+)', re.IGNORECASE)
        match = discrepancy_pattern.search(text_block)

        if match:
            num1 = int(match.group(1))
            num2 = int(match.group(2))

            if num1 > num2 * 10:  # Order of magnitude discrepancy
                alert = EpistemicCorruptionAlert(
                    alert_id=f"absorption_{hashlib.md5(text_block.encode()).hexdigest()[:8]}",
                    timestamp=datetime.utcnow().isoformat(),
                    corruption_type="absorption_overwhelm",
                    evidence_hash=hashlib.sha256(text_block.encode()).hexdigest(),
                    severity="critical",
                    location={
                        "large_count": num1,
                        "small_count": num2,
                        "discrepancy_ratio": num1 / num2 if num2 > 0 else float('inf')
                    },
                    context_window=text_block[:500],
                    confidence_score=0.9,
                    counter_measures=[
                        "Run multiple analysis methods",
                        "Flag large discrepancies as attacks",
                        "Generate violation density maps"
                    ]
                )
                alerts.append(alert)

        return alerts

    def _get_context_window(
        self, lines: List[str], center_index: int, window_size: int = 3
    ) -> List[str]:
        """Get context window around a line"""
        start = max(0, center_index - window_size)
        end = min(len(lines), center_index + window_size + 1)
        return lines[start:end]

    def compare_analysis_methods(
        self, method1_name: str, method1_results: Dict,
        method2_name: str, method2_results: Dict
    ) -> AnalysisDiscrepancy:
        """Compare two analysis methods and record discrepancies"""

        # Extract violation counts
        count1 = method1_results.get("violation_count", 0)
        count2 = method2_results.get("violation_count", 0)

        # Calculate discrepancy
        if count1 == 0 and count2 == 0:
            discrepancy_magnitude = 0.0
        elif count1 == 0 or count2 == 0:
            discrepancy_magnitude = 1.0
        else:
            discrepancy_magnitude = abs(count1 - count2) / max(count1, count2)

        # Determine likely cause
        if discrepancy_magnitude > 0.5:
            if count1 == 1 and count2 > 100:
                likely_cause = "absorption_overwhelm_attack"
            elif count1 > count2 * 10:
                likely_cause = "false_negative_attack"
            elif count2 > count1 * 10:
                likely_cause = "false_positive_attack"
            else:
                likely_cause = "epistemic_corruption"
        else:
            likely_cause = "normal_variance"

        discrepancy = AnalysisDiscrepancy(
            discrepancy_id=f"disc_{hashlib.md5(str(datetime.utcnow()).encode()).hexdigest()[:8]}",
            timestamp=datetime.utcnow().isoformat(),
            analysis_method_1=method1_name,
            analysis_method_2=method2_name,
            result_1=count1,
            result_2=count2,
            discrepancy_magnitude=discrepancy_magnitude,
            evidence_hash=hashlib.sha256(
                f"{method1_name}:{count1}:{method2_name}:{count2}".encode()
            ).hexdigest(),
            likely_cause=likely_cause
        )

        self.discrepancies.append(discrepancy)
        return discrepancy

    def generate_violation_density_map(
        self, violations: List[Dict], file_size: int, sample_size: int = 10000000
    ) -> Dict:
        """Generate violation density visualization data"""

        if not violations:
            return {"error": "No violations provided"}

        # Group violations by approximate location in file
        density_bins = 10
        bin_size = sample_size / density_bins

        density_data = {f"bin_{i}": 0 for i in range(density_bins)}

        for violation in violations:
            line_num = violation.get("line_number", 0)
            # Approximate position in file (assuming uniform line distribution)
            position_ratio = line_num / 1000000  # Rough estimate
            bin_index = min(int(position_ratio * density_bins), density_bins - 1)
            density_data[f"bin_{bin_index}"] += 1

        # Calculate statistics
        total_violations = len(violations)
        max_density = max(density_data.values())
        min_density = min(density_data.values())
        avg_density = total_violations / density_bins

        return {
            "density_bins": density_data,
            "statistics": {
                "total_violations": total_violations,
                "max_density": max_density,
                "min_density": min_density,
                "avg_density": avg_density,
                "density_variance": max_density - min_density,
                "file_size_bytes": file_size,
                "sample_size_bytes": sample_size,
                "violations_per_mb": total_violations / (sample_size / 1000000)
            },
            "visualization_ready": True,
            "generated": datetime.utcnow().isoformat()
        }

    def save_alerts_report(self, output_path: Path) -> Path:
        """Save all alerts to a report file"""
        report = {
            "report_id": f"gaslighting_alerts_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
            "generated": datetime.utcnow().isoformat(),
            "total_alerts": len(self.alerts),
            "alerts_by_type": {},
            "alerts": [vars(alert) for alert in self.alerts],
            "discrepancies": [vars(disc) for disc in self.discrepancies],
            "summary": self._generate_summary()
        }

        # Count alerts by type
        for alert in self.alerts:
            corr_type = alert.corruption_type
            report["alerts_by_type"][corr_type] = report["alerts_by_type"].get(corr_type, 0) + 1

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2)

        return output_path

    def _generate_summary(self) -> Dict:
        """Generate summary of findings"""
        total_alerts = len(self.alerts)
        critical_alerts = sum(1 for a in self.alerts if a.severity == "critical")
        high_alerts = sum(1 for a in self.alerts if a.severity == "high")

        return {
            "total_epistemic_corruption_alerts": total_alerts,
            "critical_alerts": critical_alerts,
            "high_alerts": high_alerts,
            "attack_patterns_detected": list(set(a.corruption_type for a in self.alerts)),
            "recommended_actions": [
                "Review all decoy violation alerts",
                "Validate line number consistency",
                "Run multiple analysis methods for comparison",
                "Generate violation density maps for large files",
                "Update forgiveness system with anti-gaslighting layer"
            ]
        }


def main():
    """Example usage of the gaslighting detector"""
    detector = GaslightingDetector(Path("."))

    # Example: Detect the "404 vs 1" attack
    attack_text = """
    The forgiveness system found only 1 violation in 44MB file.
    But debug analysis found 404 violations in first 10MB.
    This is a 404 vs 1 discrepancy indicating absorption attack.
    """

    corruption_score, evidence_hash, alerts = detector.detect_epistemic_corruption(
        attack_text,
        line_numbers=[1, 2, 3, 4],
        analysis_context={
            "reported_line": 348201,
            "actual_line": 348203,
            "file_size": 43950937
