#!/usr/bin/env python3
"""
Successor Readiness Tests
==========================

Tests generated per the SUCCESSOR_VERIFICATION.yaml protocol.
Every AI session must pass these before making code changes.

Failure here means the previous session left an inconsistency that must
be diagnosed before proceeding.

These tests cover:
  - Hash manifest existence and content (session: pr60_5)
  - Zone cluster integrity from Phase 7 output (session: pr60_5)
  - Classification stability for canonical files (session: pr60_5)
  - SUCCESSOR_VERIFICATION.yaml file presence

Usage:
    python3 -m pytest tests/test_successor_readiness.py -v
"""

import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).parent.parent
GRAPH_PATH = REPO_ROOT / "topology_graph.json"
MANIFEST_PATH = REPO_ROOT / "canonical" / "hash_manifest.json"
SUCCESSOR_YAML_PATH = REPO_ROOT / "SUCCESSOR_VERIFICATION.yaml"


# ── Helpers ────────────────────────────────────────────────────────────────────

def load_live_graph():
    """Load topology_graph.json, skip if absent."""
    if not GRAPH_PATH.exists():
        pytest.skip(f"topology_graph.json not found at {GRAPH_PATH}")
    with open(GRAPH_PATH) as f:
        return json.load(f)


# ── Successor test: hash manifest integrity (session pr60_5) ───────────────────

def test_hash_manifest_exists_from_pr60_5():
    """
    Successor readiness check generated by session pr60_5 at 2026-03-05.
    canonical/hash_manifest.json must exist after running the pipeline.
    """
    assert MANIFEST_PATH.exists(), (
        f"canonical/hash_manifest.json not found at {MANIFEST_PATH}. "
        "Run: python3 generate_perceivable_infinity.py . "
        "to regenerate the pipeline output."
    )


def test_hash_manifest_covers_critical_nodes_from_pr60_5():
    """
    Successor readiness check generated by session pr60_5 at 2026-03-05.
    canonical/hash_manifest.json must cover COVENANT_ROOT and GUARDIAN_SYSTEM nodes.
    """
    if not MANIFEST_PATH.exists():
        pytest.skip(f"canonical/hash_manifest.json not found — run pipeline first")

    manifest = json.loads(MANIFEST_PATH.read_text())

    assert "nodes" in manifest, "hash_manifest.json must have a 'nodes' key"
    assert "metadata" in manifest, "hash_manifest.json must have a 'metadata' key"
    assert len(manifest["nodes"]) >= 1, "hash_manifest must contain at least one hashed node"

    # At least one COVENANT_ROOT or GUARDIAN_SYSTEM must be hashed
    critical_hashed = [
        k for k, v in manifest["nodes"].items()
        if v.get("node_class") in ("COVENANT_ROOT", "GUARDIAN_SYSTEM", "EVIDENCE_ARTIFACT")
    ]
    assert len(critical_hashed) >= 1, (
        "No covenant-critical nodes (COVENANT_ROOT / GUARDIAN_SYSTEM / EVIDENCE_ARTIFACT) "
        "found in hash_manifest.json. Phase 6 of the scanner may not have run."
    )


def test_hash_manifest_has_valid_sha256_from_pr60_5():
    """
    Successor readiness check generated by session pr60_5 at 2026-03-05.
    All entries in canonical/hash_manifest.json must have valid SHA-256 hashes.
    """
    if not MANIFEST_PATH.exists():
        pytest.skip("canonical/hash_manifest.json not found — run pipeline first")

    manifest = json.loads(MANIFEST_PATH.read_text())
    nodes = manifest.get("nodes", {})

    for file_id, entry in nodes.items():
        sha = entry.get("sha256")
        assert sha is not None, f"Node {file_id!r} has null sha256 in manifest"
        assert len(sha) == 64, (
            f"Node {file_id!r} has invalid SHA-256 length {len(sha)} (expected 64)"
        )
        assert all(c in "0123456789abcdef" for c in sha), (
            f"Node {file_id!r} sha256 {sha!r} contains invalid characters"
        )


# ── Successor test: zone cluster integrity (session pr60_5) ───────────────────

def test_zone_1_immutable_authority_cluster_integrity_from_pr60_5():
    """
    Successor zone integrity check generated by session pr60_5 at 2026-03-05.
    Zone 1 (immutable authority) must have at least 1 node in the cluster summary.
    """
    graph = load_live_graph()
    clusters = graph.get("clusters", {})

    assert "zone_1_immutable_authority" in clusters, (
        "zone_1_immutable_authority not found in topology_graph.json clusters. "
        "Phase 7 (cluster aggregation) may not have run."
    )

    z1 = clusters["zone_1_immutable_authority"]
    assert z1.get("total_node_count", 0) >= 1, (
        "Zone 1 cluster has 0 nodes — COVENANT_ROOT must exist."
    )


def test_zone_4_forgiveness_grace_cluster_integrity_from_pr60_5():
    """
    Successor zone integrity check generated by session pr60_5 at 2026-03-05.
    Zone 4 (forgiveness/grace) must have at least 1 node in the cluster summary.
    """
    graph = load_live_graph()
    clusters = graph.get("clusters", {})

    assert "zone_4_forgiveness_grace" in clusters, (
        "zone_4_forgiveness_grace not found in topology_graph.json clusters."
    )

    z4 = clusters["zone_4_forgiveness_grace"]
    assert z4.get("total_node_count", 0) >= 1, (
        "Zone 4 cluster has 0 nodes — FORGIVENESS_MODULE files must exist."
    )


def test_all_zone_clusters_have_required_fields_from_pr60_5():
    """
    Successor readiness check generated by session pr60_5 at 2026-03-05.
    Each zone cluster must have the required fields from Phase 7.
    """
    graph = load_live_graph()
    clusters = graph.get("clusters", {})

    assert len(clusters) >= 1, "topology_graph.json must contain at least one cluster"

    required_fields = {"zone_id", "total_node_count", "hash_verified_count",
                       "class_distribution", "representative_sample"}

    for zone_id, cluster in clusters.items():
        missing = required_fields - set(cluster.keys())
        assert not missing, (
            f"Zone cluster {zone_id!r} is missing fields: {missing}. "
            "Check topology_scanner._aggregate_clusters()."
        )
        assert cluster["total_node_count"] >= 0
        assert isinstance(cluster["representative_sample"], list)


# ── Successor test: classification stability (session pr60_5) ─────────────────

def test_classification_stable_invariants_json_from_pr60_5():
    """
    Classification stability check generated by session pr60_5 at 2026-03-05.
    INVARIANTS.json must remain classified as COVENANT_ROOT.
    """
    graph = load_live_graph()
    node = graph["nodes"].get("INVARIANTS.json")
    if node is None:
        pytest.skip("INVARIANTS.json not found in graph")
    assert node["node_class"] == "COVENANT_ROOT", (
        f"Classification changed: {node['node_class']} != COVENANT_ROOT"
    )


def test_classification_stable_guardian_from_pr60_5():
    """
    Classification stability check generated by session pr60_5 at 2026-03-05.
    JESUS_REALITY_GUARDIAN.py must remain classified as GUARDIAN_SYSTEM.
    """
    graph = load_live_graph()
    node = graph["nodes"].get("JESUS_REALITY_GUARDIAN.py")
    if node is None:
        pytest.skip("JESUS_REALITY_GUARDIAN.py not found in graph")
    assert node["node_class"] == "GUARDIAN_SYSTEM", (
        f"Classification changed: {node['node_class']} != GUARDIAN_SYSTEM"
    )


# ── Successor test: SUCCESSOR_VERIFICATION.yaml presence ─────────────────────

def test_successor_verification_yaml_present_from_pr60_5():
    """
    Successor readiness check generated by session pr60_5 at 2026-03-05.
    SUCCESSOR_VERIFICATION.yaml must exist in the repository root.
    """
    assert SUCCESSOR_YAML_PATH.exists(), (
        f"SUCCESSOR_VERIFICATION.yaml not found at {SUCCESSOR_YAML_PATH}. "
        "This file is required for session continuity."
    )


# ── Successor test: graph has clusters key (Phase 7 output) ───────────────────

def test_topology_graph_has_clusters_key_from_pr60_5():
    """
    Successor readiness check generated by session pr60_5 at 2026-03-05.
    topology_graph.json must contain a 'clusters' key (Phase 7 output).
    """
    graph = load_live_graph()
    assert "clusters" in graph, (
        "topology_graph.json is missing the 'clusters' key. "
        "Phase 7 (cluster aggregation) was not run. "
        "Re-run: python3 generate_perceivable_infinity.py ."
    )


def test_topology_graph_has_pipeline_version_from_pr60_5():
    """
    Successor readiness check generated by session pr60_5 at 2026-03-05.
    topology_graph.json metadata must show pipeline_version 2.0.0 or higher.
    """
    graph = load_live_graph()
    metadata = graph.get("metadata", {})
    version = metadata.get("pipeline_version", "1.0.0")
    major = int(version.split(".")[0])
    assert major >= 2, (
        f"topology_graph.json pipeline_version={version!r}. "
        "Expected >= 2.0.0 (PR #60.5 scanner). "
        "Re-run: python3 generate_perceivable_infinity.py ."
    )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
