#!/usr/bin/env python3
"""
Log Analysis Example: Pattern Discovery from Pipeline Audit Logs

This script demonstrates how to analyze JSONL audit logs produced by PIPELINE_LOGGER.py
to discover common parameter change patterns and relationships.

This is a simple analytics demo, not an autonomous refactor tool.
It operates in read-only mode and produces a summary of discovered patterns.

Usage:
    python examples/log_analysis_example.py

Output:
    examples/log_analysis_summary.txt - Summary of discovered patterns
Log Analysis Example - Non-Destructive Analytics Script

Safety Notice: This script is READ-ONLY. It ingests JSONL audit logs and produces
a summary JSON file. It does NOT modify any repository files or make network calls.

Purpose: Demonstrate pattern detection in pipeline logs for autonomous evolution.
Input: hello_world_handling_pipeline.jsonl (generated by logger.py)
Output: examples/log_analysis_summary.json (summary statistics only)

Usage:
    python examples/log_analysis_example.py
Log Analysis Example

Demonstrates how to analyze CAS operation logs for insights and debugging.
Example script demonstrating how to analyze pipeline JSONL logs.

This script shows how to:
- Read JSONL pipeline logs
- Extract key metrics
- Identify errors and warnings
- Generate summaries

Usage: python log_analysis_example.py [log_file]
"""

import json
import sys
from pathlib import Path
from collections import defaultdict
from datetime import datetime

# Non-destructive operation: read-only analysis
DRY_RUN_MODE = True


def read_jsonl_logs(log_file_path):
    """
    Read JSONL log file and return list of parsed entries.
    
    Args:
        log_file_path: Path to JSONL log file
    
    Returns:
        List of dictionaries, one per log entry
    """
    entries = []
    
    if not Path(log_file_path).exists():
        print(f"⚠️  Log file not found: {log_file_path}")
        print(f"ℹ️  Creating sample log file for demonstration...")
        create_sample_log(log_file_path)
    
    try:
        with open(log_file_path, 'r') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                    entries.append(entry)
                except json.JSONDecodeError as e:
                    print(f"⚠️  Skipping invalid JSON at line {line_num}: {e}")
                    continue
    except Exception as e:
        print(f"❌ Error reading log file: {e}")
        return []
    
    return entries


def create_sample_log(log_file_path):
    """Create a sample log file for demonstration purposes."""
    sample_entries = [
        {
            "timestamp": "2026-01-15T10:30:00Z",
            "action": "parameter_change",
            "file": "src/physics/vehicle.py",
            "function": "update_vehicle_properties",
            "parameters": {
                "fMass": {"old": 1500.0, "new": 1800.0},
                "fDriveInertia": {"old": 2.5, "new": 3.0}
            },
            "actor": "manual_update",
            "commit": "abc123"
        },
        {
            "timestamp": "2026-01-16T14:20:00Z",
            "action": "parameter_change",
            "file": "src/physics/vehicle.py",
            "function": "update_vehicle_properties",
            "parameters": {
                "fMass": {"old": 1800.0, "new": 2000.0},
                "fDriveInertia": {"old": 3.0, "new": 3.5}
            },
            "actor": "automated_script",
            "commit": "def456"
        },
        {
            "timestamp": "2026-01-18T09:15:00Z",
            "action": "parameter_change",
            "file": "src/physics/truck.py",
            "function": "configure_truck",
            "parameters": {
                "fMass": {"old": 3000.0, "new": 3600.0},
                "fDriveInertia": {"old": 5.0, "new": 6.0}
            },
            "actor": "manual_update",
            "commit": "ghi789"
        },
        {
            "timestamp": "2026-01-20T16:45:00Z",
            "action": "parameter_change",
            "file": "src/physics/vehicle.py",
            "function": "update_vehicle_properties",
            "parameters": {
                "fMass": {"old": 2000.0, "new": 1600.0},
                "fDriveInertia": {"old": 3.5, "new": 2.8}
            },
            "actor": "manual_update",
            "commit": "jkl012"
        },
        {
            "timestamp": "2026-02-01T11:00:00Z",
            "action": "parameter_change",
            "file": "src/physics/car.py",
            "function": "adjust_car_physics",
            "parameters": {
                "fMass": {"old": 1200.0, "new": 1440.0},
                "fDriveInertia": {"old": 2.0, "new": 2.4}
            },
            "actor": "automated_script",
            "commit": "mno345"
        }
    ]
    
    with open(log_file_path, 'w') as f:
        for entry in sample_entries:
            f.write(json.dumps(entry) + '\n')
    
    print(f"✅ Created sample log file: {log_file_path}")


def analyze_parameter_changes(entries):
    """
    Analyze parameter change patterns from log entries.
    
    Args:
        entries: List of log entry dictionaries
    
    Returns:
        Dictionary of discovered patterns and statistics
    """
    # Track parameter changes
    parameter_changes = defaultdict(list)
    co_occurring_changes = defaultdict(lambda: defaultdict(int))
    
    for entry in entries:
        if entry.get('action') != 'parameter_change':
            continue
        
        params = entry.get('parameters', {})
        if not params:
            continue
        
        # Track individual parameter changes
        for param_name, change in params.items():
            if isinstance(change, dict) and 'old' in change and 'new' in change:
                old_val = change['old']
                new_val = change['new']
                if old_val != new_val:
                    parameter_changes[param_name].append({
                        'old': old_val,
                        'new': new_val,
                        'timestamp': entry.get('timestamp'),
                        'file': entry.get('file')
                    })
        
        # Track co-occurring parameter changes
        changed_params = [p for p, c in params.items() 
                         if isinstance(c, dict) and c.get('old') != c.get('new')]
        
        for i, param1 in enumerate(changed_params):
            for param2 in changed_params[i+1:]:
                # Store both directions for correlation analysis
                pair_key = tuple(sorted([param1, param2]))
                co_occurring_changes[pair_key][entry.get('file', 'unknown')] += 1
    
    return {
        'parameter_changes': parameter_changes,
        'co_occurring_changes': co_occurring_changes
    }


def calculate_correlation(param_changes, param1, param2):
    """
    Calculate simple correlation between two parameters.
    
    This is a simplified correlation - in production, use proper statistical methods.
    
    Args:
        param_changes: Dictionary of parameter changes
        param1: First parameter name
        param2: Second parameter name
    
    Returns:
        Dictionary with correlation statistics
    """
    changes1 = param_changes.get(param1, [])
    changes2 = param_changes.get(param2, [])
    
    if not changes1 or not changes2:
        return None
    
    # Find co-occurring changes by timestamp
    co_changes = []
    for c1 in changes1:
        for c2 in changes2:
            if c1['timestamp'] == c2['timestamp']:
                try:
                    ratio1 = c1['new'] / c1['old'] if c1['old'] != 0 else 0
                    ratio2 = c2['new'] / c2['old'] if c2['old'] != 0 else 0
                    co_changes.append({
                        'ratio1': ratio1,
                        'ratio2': ratio2,
                        'timestamp': c1['timestamp']
                    })
                except (TypeError, ZeroDivisionError):
                    continue
    
    if not co_changes:
        return None
    
    # Calculate average ratio relationship
    avg_ratio = sum(c['ratio2'] / c['ratio1'] if c['ratio1'] != 0 else 0 
                    for c in co_changes) / len(co_changes)
    
    return {
        'instances': len(co_changes),
        'average_ratio': avg_ratio,
        'confidence': 'high' if len(co_changes) >= 5 else 'medium' if len(co_changes) >= 3 else 'low'
    }


def generate_summary_report(analysis_results):
    """
    Generate a human-readable summary report of discovered patterns.
    
    Args:
        analysis_results: Dictionary from analyze_parameter_changes()
    
    Returns:
        String containing formatted summary report
    """
    report = []
    report.append("=" * 80)
    report.append("Log Analysis Summary: Parameter Change Pattern Discovery")
    report.append("=" * 80)
    report.append(f"Generated: {datetime.utcnow().isoformat()}Z")
    report.append(f"Mode: DRY-RUN (Read-only analysis)")
    report.append("")
    
    # Parameter change statistics
    param_changes = analysis_results['parameter_changes']
    report.append("## Parameter Change Frequency")
    report.append("")
    
    if param_changes:
        for param, changes in sorted(param_changes.items(), 
                                     key=lambda x: len(x[1]), 
                                     reverse=True):
            report.append(f"  - {param}: {len(changes)} changes detected")
    else:
        report.append("  (No parameter changes detected)")
    
    report.append("")
    
    # Co-occurring parameter changes
    co_changes = analysis_results['co_occurring_changes']
    report.append("## Co-occurring Parameter Changes")
    report.append("")
    
    if co_changes:
        report.append("Parameters that frequently change together:")
        report.append("")
        for param_pair, file_counts in sorted(co_changes.items(), 
                                              key=lambda x: sum(x[1].values()), 
                                              reverse=True):
            total_instances = sum(file_counts.values())
            param1, param2 = param_pair
            report.append(f"  - {param1} ↔ {param2}")
            report.append(f"    Total instances: {total_instances}")
            report.append(f"    Files affected: {len(file_counts)}")
            
            # Calculate correlation if both parameters have changes
            correlation = calculate_correlation(param_changes, param1, param2)
            if correlation:
                report.append(f"    Co-occurring changes: {correlation['instances']}")
                report.append(f"    Average ratio: {correlation['average_ratio']:.2f}")
                report.append(f"    Confidence: {correlation['confidence']}")
            report.append("")
    else:
        report.append("  (No co-occurring parameter changes detected)")
    
    report.append("")
    
    # Suggested transformations (for demonstration only)
    report.append("## Suggested Pattern-Based Transformations")
    report.append("")
    report.append("Based on discovered patterns, the following transformations")
    report.append("could be considered (requires human review):")
    report.append("")
    
    suggestions_made = False
    for param_pair, file_counts in co_changes.items():
        param1, param2 = param_pair
        correlation = calculate_correlation(param_changes, param1, param2)
        
        if correlation and correlation['confidence'] in ['high', 'medium']:
            suggestions_made = True
            report.append(f"  📊 Pattern: {param1} → {param2}")
            report.append(f"     When {param1} changes, consider adjusting {param2}")
            report.append(f"     Typical ratio: {correlation['average_ratio']:.2f}")
            report.append(f"     Evidence: {correlation['instances']} instances")
            report.append(f"     Confidence: {correlation['confidence']}")
            report.append("")
    
    if not suggestions_made:
        report.append("  (Insufficient data for high-confidence suggestions)")
        report.append("  (Minimum 3 co-occurring instances required)")
    
    report.append("")
    report.append("=" * 80)
    report.append("⚠️  IMPORTANT: This is a read-only analysis.")
    report.append("⚠️  No files have been modified.")
    report.append("⚠️  All transformations require human review and approval.")
    report.append("=" * 80)
    
    return "\n".join(report)


def main():
    """Main entry point for log analysis."""
    print("🔍 Log Analysis Example: Pattern Discovery")
    print("=" * 60)
    print()
    
    # Read log file
    log_file = Path(__file__).parent / "hello_world_handling_pipeline.jsonl"
    print(f"📖 Reading log file: {log_file}")
    
    entries = read_jsonl_logs(log_file)
    print(f"✅ Loaded {len(entries)} log entries")
    print()
    
    # Analyze patterns
    print("🔬 Analyzing parameter change patterns...")
    analysis_results = analyze_parameter_changes(entries)
    
    # Generate summary report
    print("📝 Generating summary report...")
    report = generate_summary_report(analysis_results)
    
    # Write summary to file
    output_file = Path(__file__).parent / "log_analysis_summary.txt"
    with open(output_file, 'w') as f:
        f.write(report)
    
    print(f"✅ Summary report written to: {output_file}")
    print()
    
    # Display report
    print(report)
    print()
    
    # Final status
    print("=" * 60)
    print("✅ Analysis complete!")
    print(f"📄 Results saved to: {output_file}")
    print("⚠️  No files were modified (dry-run mode)")
    print("=" * 60)
    
    return 0


if __name__ == '__main__':

def analyze_parameter_changes(jsonl_path):
    """
    Analyze JSONL log for parameter change patterns.
    
    This function is READ-ONLY. It does not modify any files.
    
    Args:
        jsonl_path: Path to JSONL log file
        
    Returns:
        Dictionary of parameter pair occurrences
    """
    print(f"[INFO] Reading log file: {jsonl_path}")
    
    # Track parameter changes by context
    context_params = defaultdict(list)
    total_entries = 0
    
    try:
        with open(jsonl_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                if not line.strip():
                    continue
                    
                try:
                    entry = json.loads(line)
                    total_entries += 1
                    
                    # Extract parameter changes
                    if entry.get('step') == 'transformation':
                        context = entry.get('context', 'unknown')
                        param = entry.get('input_param')
                        if param:
                            context_params[context].append(param)
                            
                except json.JSONDecodeError as e:
                    print(f"[WARN] Invalid JSON at line {line_num}: {e}")
                    continue
                    
    except FileNotFoundError:
        print(f"[ERROR] File not found: {jsonl_path}")
        print("[INFO] Creating sample file for demonstration...")
        create_sample_log(jsonl_path)
        # Retry after creating sample
        return analyze_parameter_changes(jsonl_path)
        
    print(f"[INFO] Processed {total_entries} log entries")
    print(f"[INFO] Found {len(context_params)} unique contexts")
    
    # Detect parameter co-variations
    param_pairs = defaultdict(int)
    
    for context, params in context_params.items():
        # Find pairs of parameters that changed together
        for i, param1 in enumerate(params):
            for param2 in params[i+1:]:
                # Normalize pair order for consistent counting
                pair = tuple(sorted([param1, param2]))
                param_pairs[pair] += 1
    
    # Convert to readable format
    result = {}
    for (param1, param2), count in param_pairs.items():
        key = f"{param1}->{param2}"
        result[key] = count
        
    print(f"[INFO] Detected {len(result)} parameter pair patterns")
    
    return result


def create_sample_log(jsonl_path):
    """
    Create a sample JSONL log file for demonstration purposes.
    
    This function writes ONLY to the examples/ directory, NOT to repository files.
    
    Args:
        jsonl_path: Path where sample log should be created
    """
    # Ensure examples directory exists
    examples_dir = Path(jsonl_path).parent
    examples_dir.mkdir(parents=True, exist_ok=True)
    
    sample_data = [
        {
            "timestamp": "2026-02-16T18:00:00Z",
            "step": "transformation",
            "input_param": "fMass",
            "old_value": 1.0,
            "new_value": 1.5,
            "context": "hello_world_v1"
        },
        {
            "timestamp": "2026-02-16T18:00:01Z",
            "step": "transformation",
            "input_param": "fDriveInertia",
            "old_value": 0.5,
            "new_value": 0.75,
            "context": "hello_world_v1"
        },
        {
            "timestamp": "2026-02-16T18:01:00Z",
            "step": "transformation",
            "input_param": "fMass",
            "old_value": 1.5,
            "new_value": 2.0,
            "context": "hello_world_v2"
        },
        {
            "timestamp": "2026-02-16T18:01:01Z",
            "step": "transformation",
            "input_param": "fDriveInertia",
            "old_value": 0.75,
            "new_value": 1.0,
            "context": "hello_world_v2"
        },
        {
            "timestamp": "2026-02-16T18:02:00Z",
            "step": "transformation",
            "input_param": "fMass",
            "old_value": 2.0,
            "new_value": 2.5,
            "context": "hello_world_v3"
        },
        {
            "timestamp": "2026-02-16T18:02:01Z",
            "step": "transformation",
            "input_param": "fDriveInertia",
            "old_value": 1.0,
            "new_value": 1.25,
            "context": "hello_world_v3"
        },
    ]
    
    # Replicate pattern 12 times to match example in docs
    extended_data = []
    for i in range(12):
        for entry in sample_data:
            extended_entry = entry.copy()
            extended_entry['context'] = f"{entry['context']}_iter{i}"
            extended_entry['timestamp'] = f"2026-02-16T{18 + (i // 4):02d}:{(i % 4) * 15:02d}:00Z"
            extended_data.append(extended_entry)
    
    print(f"[INFO] Creating sample log with {len(extended_data)} entries")
    
    with open(jsonl_path, 'w', encoding='utf-8') as f:
        for entry in extended_data:
            f.write(json.dumps(entry) + '\n')
            
    print(f"[INFO] Sample log created: {jsonl_path}")


def save_summary(summary, output_path):
    """
    Save analysis summary to JSON file.
    
    This function writes ONLY to examples/ directory, NOT to repository files.
    
    Args:
        summary: Dictionary of analysis results
        output_path: Path to output JSON file
    """
    # Ensure examples directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create complete summary with metadata
    complete_summary = {
        "analysis_timestamp": datetime.utcnow().isoformat() + "Z",
        "parameter_pair_counts": summary,
        "total_patterns": len(summary),
        "total_occurrences": sum(summary.values()),
        "metadata": {
            "script": "log_analysis_example.py",
            "purpose": "non-destructive pattern detection",
            "safety": "read-only, no repository modifications"
        }
    }
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(complete_summary, f, indent=2)
        
    print(f"[INFO] Summary saved: {output_path}")
    
    # Display summary
    print("\n" + "="*60)
    print("ANALYSIS SUMMARY")
    print("="*60)
    print(f"Total patterns detected: {complete_summary['total_patterns']}")
    print(f"Total occurrences: {complete_summary['total_occurrences']}")
    print("\nTop parameter pairs:")
    
    sorted_pairs = sorted(
        summary.items(),
        key=lambda x: x[1],
        reverse=True
    )
    
    for i, (pair, count) in enumerate(sorted_pairs[:10], 1):
        print(f"  {i}. {pair}: {count} occurrences")
    
    print("="*60)


def main():
    """
    Main function - orchestrates log analysis.
    
    Safety: This script is entirely read-only except for writing to examples/ directory.
    """
    print("="*60)
    print("Log Analysis Example - Non-Destructive Analytics")
    print("="*60)
    print()
    
    # Define paths (all in examples/ directory)
    repo_root = Path(__file__).parent.parent
    examples_dir = repo_root / "examples"
    
    input_log = examples_dir / "hello_world_handling_pipeline.jsonl"
    output_summary = examples_dir / "log_analysis_summary.json"
    
    print(f"Input log: {input_log}")
    print(f"Output summary: {output_summary}")
    print()
    
    # Analyze logs (read-only)
    summary = analyze_parameter_changes(input_log)
    
    # Save summary (writes to examples/ only)
    save_summary(summary, output_summary)
    
    print()
    print("[SUCCESS] Analysis complete")
    print(f"[INFO] Review results in: {output_summary}")
    print()
    print("Safety verification:")
    print("  ✓ No repository files modified")
    print("  ✓ No network calls made")
    print("  ✓ Only examples/ directory written to")
    print("  ✓ Analysis is reproducible and deterministic")
    
    return 0
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List


def load_jsonl_logs(log_file: Path) -> List[Dict]:
    """Load JSONL log file."""
    logs = []
    
    if not log_file.exists():
        print(f"Log file not found: {log_file}")
        return logs
    
    with open(log_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    logs.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"Warning: Failed to parse log line: {e}")
    
    return logs


def analyze_operations(logs: List[Dict]) -> Dict:
    """Analyze operation types and frequencies."""
    operation_counts = Counter()
    operation_errors = Counter()
    
    for log in logs:
        level = log.get("level", "INFO")
        message = log.get("message", "")
        
        # Count operations
        if "operation" in log:
            operation_counts[log["operation"]] += 1
        
        # Count errors
        if level == "ERROR":
            operation_errors[message] += 1
    
    return {
        "operation_counts": dict(operation_counts),
        "error_counts": dict(operation_errors),
        "total_logs": len(logs)
    }


def analyze_timing(logs: List[Dict]) -> Dict:
    """Analyze operation timing patterns."""
    if not logs:
        return {}
    
    timestamps = []
    for log in logs:
        if "timestamp" in log:
            try:
                ts = datetime.fromisoformat(log["timestamp"].replace('Z', '+00:00'))
                timestamps.append(ts)
            except ValueError:
                pass
    
    if not timestamps:
        return {}
    
    timestamps.sort()
    
    # Calculate time between operations
    intervals = []
    for i in range(1, len(timestamps)):
        interval = (timestamps[i] - timestamps[i-1]).total_seconds()
        intervals.append(interval)
    
    return {
        "first_operation": timestamps[0].isoformat(),
        "last_operation": timestamps[-1].isoformat(),
        "total_duration_seconds": (timestamps[-1] - timestamps[0]).total_seconds(),
        "average_interval_seconds": sum(intervals) / len(intervals) if intervals else 0,
        "operation_count": len(timestamps)
    }


def analyze_file_operations(logs: List[Dict]) -> Dict:
    """Analyze file-related operations."""
    files_processed = set()
    files_with_errors = set()
    operations_by_file = defaultdict(list)
    
    for log in logs:
        # Extract file references
        filepath = log.get("filepath") or log.get("file") or log.get("path")
        
        if filepath:
            files_processed.add(filepath)
            
            operation = log.get("operation", "unknown")
            operations_by_file[filepath].append(operation)
            
            if log.get("level") == "ERROR":
                files_with_errors.add(filepath)
    
    return {
        "total_files_processed": len(files_processed),
        "files_with_errors": len(files_with_errors),
        "operations_per_file": {
            f: len(ops) for f, ops in operations_by_file.items()
        }
    }


def generate_report(log_file: Path, output_file: Path = None):
    """Generate comprehensive log analysis report."""
    print(f"Analyzing log file: {log_file}")
    
    logs = load_jsonl_logs(log_file)
    
    if not logs:
        print("No logs found to analyze")
        return
    
    print(f"Loaded {len(logs)} log entries")
    
    # Perform analyses
    operation_analysis = analyze_operations(logs)
    timing_analysis = analyze_timing(logs)
    file_analysis = analyze_file_operations(logs)
    
    # Compile report
    report = {
        "log_file": str(log_file),
        "analyzed_at": datetime.utcnow().isoformat() + "Z",
        "summary": {
            "total_logs": len(logs),
            "operations": operation_analysis,
            "timing": timing_analysis,
            "files": file_analysis
        }
    }
    
    # Print summary
    print("\n" + "=" * 60)
    print("LOG ANALYSIS REPORT")
    print("=" * 60)
    print(f"\nTotal logs: {len(logs)}")
    
    print("\nOperation counts:")
    for op, count in operation_analysis["operation_counts"].items():
        print(f"  {op}: {count}")
    
    if operation_analysis["error_counts"]:
        print("\nErrors:")
        for error, count in operation_analysis["error_counts"].items():
            print(f"  {error}: {count}")
    
    if timing_analysis:
        print("\nTiming:")
        print(f"  Duration: {timing_analysis.get('total_duration_seconds', 0):.2f}s")
        print(f"  Operations: {timing_analysis.get('operation_count', 0)}")
        print(f"  Avg interval: {timing_analysis.get('average_interval_seconds', 0):.3f}s")
    
    print("\nFile operations:")
    print(f"  Files processed: {file_analysis['total_files_processed']}")
    print(f"  Files with errors: {file_analysis['files_with_errors']}")
    
    # Save report if output file specified
    if output_file:
        output_file = Path(output_file)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2)
        
        print(f"\nReport saved to: {output_file}")
    
    print("=" * 60)
    
    return report


def main():
    """Main function."""
    if len(sys.argv) < 2:
        print("Usage: python log_analysis_example.py <log_file> [output_file]")
        print("\nExample:")
        print("  python log_analysis_example.py logs/pipeline_20260216.jsonl")
        print("  python log_analysis_example.py logs/pipeline_20260216.jsonl analysis_report.json")
        sys.exit(1)
    
    log_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else None
    
    try:
        generate_report(log_file, output_file)
    except Exception as e:
        print(f"Error during analysis: {e}")
        raise


if __name__ == "__main__":
    main()
from collections import defaultdict
from pathlib import Path
from datetime import datetime


def parse_iso8601(timestamp_str):
    """Parse ISO8601 timestamp."""
    try:
        return datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
    except:
        return None


def analyze_log(log_path):
    """Analyze a pipeline log file."""
    if not Path(log_path).exists():
        print(f"Error: Log file not found: {log_path}")
        return None
    
    stats = {
        'total_steps': 0,
        'by_status': defaultdict(int),
        'by_step_name': defaultdict(int),
        'errors': [],
        'start_time': None,
        'end_time': None,
        'duration_seconds': None
    }
    
    print(f"Analyzing log: {log_path}")
    print("=" * 60)
    
    with open(log_path, 'r') as f:
        for line in f:
            try:
                entry = json.loads(line)
                
                stats['total_steps'] += 1
                stats['by_status'][entry['status']] += 1
                stats['by_step_name'][entry['step_name']] += 1
                
                # Track errors
                if entry['status'] == 'failed':
                    stats['errors'].append({
                        'step_id': entry['step_id'],
                        'step_name': entry['step_name'],
                        'error': entry.get('error', 'Unknown error'),
                        'timestamp': entry['timestamp']
                    })
                
                # Track timing
                timestamp = parse_iso8601(entry['timestamp'])
                if timestamp:
                    if stats['start_time'] is None or timestamp < stats['start_time']:
                        stats['start_time'] = timestamp
                    if stats['end_time'] is None or timestamp > stats['end_time']:
                        stats['end_time'] = timestamp
                
            except json.JSONDecodeError:
                print(f"Warning: Invalid JSON line: {line[:50]}...")
            except Exception as e:
                print(f"Warning: Error parsing line: {e}")
    
    # Calculate duration
    if stats['start_time'] and stats['end_time']:
        duration = stats['end_time'] - stats['start_time']
        stats['duration_seconds'] = duration.total_seconds()
    
    return stats


def print_summary(stats):
    """Print analysis summary."""
    print(f"\nTotal Steps: {stats['total_steps']}")
    
    print("\nBy Status:")
    for status, count in sorted(stats['by_status'].items()):
        print(f"  {status:12} {count:>5}")
    
    print("\nBy Step Name:")
    for step_name, count in sorted(stats['by_step_name'].items(), key=lambda x: -x[1]):
        print(f"  {step_name:30} {count:>5}")
    
    if stats['start_time']:
        print(f"\nStart Time: {stats['start_time'].isoformat()}")
    if stats['end_time']:
        print(f"End Time:   {stats['end_time'].isoformat()}")
    if stats['duration_seconds'] is not None:
        print(f"Duration:   {stats['duration_seconds']:.2f} seconds")
    
    if stats['errors']:
        print(f"\nErrors ({len(stats['errors'])}):")
        for error in stats['errors']:
            print(f"  Step {error['step_id']} ({error['step_name']}): {error['error']}")
    else:
        print("\n✓ No errors found")
    
    print("\n" + "=" * 60)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        # Default to example log
        log_file = "logs/indexing_pipeline.jsonl"
        print(f"No log file specified. Using default: {log_file}")
    else:
        log_file = sys.argv[1]
    
    stats = analyze_log(log_file)
    
    if stats:
        print_summary(stats)
        return 0
    else:
        return 1


if __name__ == "__main__":
    sys.exit(main())
