#!/usr/bin/env python3
"""
Log Analysis Example - Non-Destructive Analytics Script

Safety Notice: This script is READ-ONLY. It ingests JSONL audit logs and produces
a summary JSON file. It does NOT modify any repository files or make network calls.

Purpose: Demonstrate pattern detection in pipeline logs for autonomous evolution.
Input: hello_world_handling_pipeline.jsonl (generated by logger.py)
Output: examples/log_analysis_summary.json (summary statistics only)

Usage:
    python examples/log_analysis_example.py
Log Analysis Example

Demonstrates how to analyze CAS operation logs for insights and debugging.
Example script demonstrating how to analyze pipeline JSONL logs.

This script shows how to:
- Read JSONL pipeline logs
- Extract key metrics
- Identify errors and warnings
- Generate summaries

Usage: python log_analysis_example.py [log_file]
"""

import json
import sys
from pathlib import Path
from collections import defaultdict
from datetime import datetime


def analyze_parameter_changes(jsonl_path):
    """
    Analyze JSONL log for parameter change patterns.
    
    This function is READ-ONLY. It does not modify any files.
    
    Args:
        jsonl_path: Path to JSONL log file
        
    Returns:
        Dictionary of parameter pair occurrences
    """
    print(f"[INFO] Reading log file: {jsonl_path}")
    
    # Track parameter changes by context
    context_params = defaultdict(list)
    total_entries = 0
    
    try:
        with open(jsonl_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                if not line.strip():
                    continue
                    
                try:
                    entry = json.loads(line)
                    total_entries += 1
                    
                    # Extract parameter changes
                    if entry.get('step') == 'transformation':
                        context = entry.get('context', 'unknown')
                        param = entry.get('input_param')
                        if param:
                            context_params[context].append(param)
                            
                except json.JSONDecodeError as e:
                    print(f"[WARN] Invalid JSON at line {line_num}: {e}")
                    continue
                    
    except FileNotFoundError:
        print(f"[ERROR] File not found: {jsonl_path}")
        print("[INFO] Creating sample file for demonstration...")
        create_sample_log(jsonl_path)
        # Retry after creating sample
        return analyze_parameter_changes(jsonl_path)
        
    print(f"[INFO] Processed {total_entries} log entries")
    print(f"[INFO] Found {len(context_params)} unique contexts")
    
    # Detect parameter co-variations
    param_pairs = defaultdict(int)
    
    for context, params in context_params.items():
        # Find pairs of parameters that changed together
        for i, param1 in enumerate(params):
            for param2 in params[i+1:]:
                # Normalize pair order for consistent counting
                pair = tuple(sorted([param1, param2]))
                param_pairs[pair] += 1
    
    # Convert to readable format
    result = {}
    for (param1, param2), count in param_pairs.items():
        key = f"{param1}->{param2}"
        result[key] = count
        
    print(f"[INFO] Detected {len(result)} parameter pair patterns")
    
    return result


def create_sample_log(jsonl_path):
    """
    Create a sample JSONL log file for demonstration purposes.
    
    This function writes ONLY to the examples/ directory, NOT to repository files.
    
    Args:
        jsonl_path: Path where sample log should be created
    """
    # Ensure examples directory exists
    examples_dir = Path(jsonl_path).parent
    examples_dir.mkdir(parents=True, exist_ok=True)
    
    sample_data = [
        {
            "timestamp": "2026-02-16T18:00:00Z",
            "step": "transformation",
            "input_param": "fMass",
            "old_value": 1.0,
            "new_value": 1.5,
            "context": "hello_world_v1"
        },
        {
            "timestamp": "2026-02-16T18:00:01Z",
            "step": "transformation",
            "input_param": "fDriveInertia",
            "old_value": 0.5,
            "new_value": 0.75,
            "context": "hello_world_v1"
        },
        {
            "timestamp": "2026-02-16T18:01:00Z",
            "step": "transformation",
            "input_param": "fMass",
            "old_value": 1.5,
            "new_value": 2.0,
            "context": "hello_world_v2"
        },
        {
            "timestamp": "2026-02-16T18:01:01Z",
            "step": "transformation",
            "input_param": "fDriveInertia",
            "old_value": 0.75,
            "new_value": 1.0,
            "context": "hello_world_v2"
        },
        {
            "timestamp": "2026-02-16T18:02:00Z",
            "step": "transformation",
            "input_param": "fMass",
            "old_value": 2.0,
            "new_value": 2.5,
            "context": "hello_world_v3"
        },
        {
            "timestamp": "2026-02-16T18:02:01Z",
            "step": "transformation",
            "input_param": "fDriveInertia",
            "old_value": 1.0,
            "new_value": 1.25,
            "context": "hello_world_v3"
        },
    ]
    
    # Replicate pattern 12 times to match example in docs
    extended_data = []
    for i in range(12):
        for entry in sample_data:
            extended_entry = entry.copy()
            extended_entry['context'] = f"{entry['context']}_iter{i}"
            extended_entry['timestamp'] = f"2026-02-16T{18 + (i // 4):02d}:{(i % 4) * 15:02d}:00Z"
            extended_data.append(extended_entry)
    
    print(f"[INFO] Creating sample log with {len(extended_data)} entries")
    
    with open(jsonl_path, 'w', encoding='utf-8') as f:
        for entry in extended_data:
            f.write(json.dumps(entry) + '\n')
            
    print(f"[INFO] Sample log created: {jsonl_path}")


def save_summary(summary, output_path):
    """
    Save analysis summary to JSON file.
    
    This function writes ONLY to examples/ directory, NOT to repository files.
    
    Args:
        summary: Dictionary of analysis results
        output_path: Path to output JSON file
    """
    # Ensure examples directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create complete summary with metadata
    complete_summary = {
        "analysis_timestamp": datetime.utcnow().isoformat() + "Z",
        "parameter_pair_counts": summary,
        "total_patterns": len(summary),
        "total_occurrences": sum(summary.values()),
        "metadata": {
            "script": "log_analysis_example.py",
            "purpose": "non-destructive pattern detection",
            "safety": "read-only, no repository modifications"
        }
    }
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(complete_summary, f, indent=2)
        
    print(f"[INFO] Summary saved: {output_path}")
    
    # Display summary
    print("\n" + "="*60)
    print("ANALYSIS SUMMARY")
    print("="*60)
    print(f"Total patterns detected: {complete_summary['total_patterns']}")
    print(f"Total occurrences: {complete_summary['total_occurrences']}")
    print("\nTop parameter pairs:")
    
    sorted_pairs = sorted(
        summary.items(),
        key=lambda x: x[1],
        reverse=True
    )
    
    for i, (pair, count) in enumerate(sorted_pairs[:10], 1):
        print(f"  {i}. {pair}: {count} occurrences")
    
    print("="*60)


def main():
    """
    Main function - orchestrates log analysis.
    
    Safety: This script is entirely read-only except for writing to examples/ directory.
    """
    print("="*60)
    print("Log Analysis Example - Non-Destructive Analytics")
    print("="*60)
    print()
    
    # Define paths (all in examples/ directory)
    repo_root = Path(__file__).parent.parent
    examples_dir = repo_root / "examples"
    
    input_log = examples_dir / "hello_world_handling_pipeline.jsonl"
    output_summary = examples_dir / "log_analysis_summary.json"
    
    print(f"Input log: {input_log}")
    print(f"Output summary: {output_summary}")
    print()
    
    # Analyze logs (read-only)
    summary = analyze_parameter_changes(input_log)
    
    # Save summary (writes to examples/ only)
    save_summary(summary, output_summary)
    
    print()
    print("[SUCCESS] Analysis complete")
    print(f"[INFO] Review results in: {output_summary}")
    print()
    print("Safety verification:")
    print("  ✓ No repository files modified")
    print("  ✓ No network calls made")
    print("  ✓ Only examples/ directory written to")
    print("  ✓ Analysis is reproducible and deterministic")
    
    return 0
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List


def load_jsonl_logs(log_file: Path) -> List[Dict]:
    """Load JSONL log file."""
    logs = []
    
    if not log_file.exists():
        print(f"Log file not found: {log_file}")
        return logs
    
    with open(log_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    logs.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"Warning: Failed to parse log line: {e}")
    
    return logs


def analyze_operations(logs: List[Dict]) -> Dict:
    """Analyze operation types and frequencies."""
    operation_counts = Counter()
    operation_errors = Counter()
    
    for log in logs:
        level = log.get("level", "INFO")
        message = log.get("message", "")
        
        # Count operations
        if "operation" in log:
            operation_counts[log["operation"]] += 1
        
        # Count errors
        if level == "ERROR":
            operation_errors[message] += 1
    
    return {
        "operation_counts": dict(operation_counts),
        "error_counts": dict(operation_errors),
        "total_logs": len(logs)
    }


def analyze_timing(logs: List[Dict]) -> Dict:
    """Analyze operation timing patterns."""
    if not logs:
        return {}
    
    timestamps = []
    for log in logs:
        if "timestamp" in log:
            try:
                ts = datetime.fromisoformat(log["timestamp"].replace('Z', '+00:00'))
                timestamps.append(ts)
            except ValueError:
                pass
    
    if not timestamps:
        return {}
    
    timestamps.sort()
    
    # Calculate time between operations
    intervals = []
    for i in range(1, len(timestamps)):
        interval = (timestamps[i] - timestamps[i-1]).total_seconds()
        intervals.append(interval)
    
    return {
        "first_operation": timestamps[0].isoformat(),
        "last_operation": timestamps[-1].isoformat(),
        "total_duration_seconds": (timestamps[-1] - timestamps[0]).total_seconds(),
        "average_interval_seconds": sum(intervals) / len(intervals) if intervals else 0,
        "operation_count": len(timestamps)
    }


def analyze_file_operations(logs: List[Dict]) -> Dict:
    """Analyze file-related operations."""
    files_processed = set()
    files_with_errors = set()
    operations_by_file = defaultdict(list)
    
    for log in logs:
        # Extract file references
        filepath = log.get("filepath") or log.get("file") or log.get("path")
        
        if filepath:
            files_processed.add(filepath)
            
            operation = log.get("operation", "unknown")
            operations_by_file[filepath].append(operation)
            
            if log.get("level") == "ERROR":
                files_with_errors.add(filepath)
    
    return {
        "total_files_processed": len(files_processed),
        "files_with_errors": len(files_with_errors),
        "operations_per_file": {
            f: len(ops) for f, ops in operations_by_file.items()
        }
    }


def generate_report(log_file: Path, output_file: Path = None):
    """Generate comprehensive log analysis report."""
    print(f"Analyzing log file: {log_file}")
    
    logs = load_jsonl_logs(log_file)
    
    if not logs:
        print("No logs found to analyze")
        return
    
    print(f"Loaded {len(logs)} log entries")
    
    # Perform analyses
    operation_analysis = analyze_operations(logs)
    timing_analysis = analyze_timing(logs)
    file_analysis = analyze_file_operations(logs)
    
    # Compile report
    report = {
        "log_file": str(log_file),
        "analyzed_at": datetime.utcnow().isoformat() + "Z",
        "summary": {
            "total_logs": len(logs),
            "operations": operation_analysis,
            "timing": timing_analysis,
            "files": file_analysis
        }
    }
    
    # Print summary
    print("\n" + "=" * 60)
    print("LOG ANALYSIS REPORT")
    print("=" * 60)
    print(f"\nTotal logs: {len(logs)}")
    
    print("\nOperation counts:")
    for op, count in operation_analysis["operation_counts"].items():
        print(f"  {op}: {count}")
    
    if operation_analysis["error_counts"]:
        print("\nErrors:")
        for error, count in operation_analysis["error_counts"].items():
            print(f"  {error}: {count}")
    
    if timing_analysis:
        print("\nTiming:")
        print(f"  Duration: {timing_analysis.get('total_duration_seconds', 0):.2f}s")
        print(f"  Operations: {timing_analysis.get('operation_count', 0)}")
        print(f"  Avg interval: {timing_analysis.get('average_interval_seconds', 0):.3f}s")
    
    print("\nFile operations:")
    print(f"  Files processed: {file_analysis['total_files_processed']}")
    print(f"  Files with errors: {file_analysis['files_with_errors']}")
    
    # Save report if output file specified
    if output_file:
        output_file = Path(output_file)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2)
        
        print(f"\nReport saved to: {output_file}")
    
    print("=" * 60)
    
    return report


def main():
    """Main function."""
    if len(sys.argv) < 2:
        print("Usage: python log_analysis_example.py <log_file> [output_file]")
        print("\nExample:")
        print("  python log_analysis_example.py logs/pipeline_20260216.jsonl")
        print("  python log_analysis_example.py logs/pipeline_20260216.jsonl analysis_report.json")
        sys.exit(1)
    
    log_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else None
    
    try:
        generate_report(log_file, output_file)
    except Exception as e:
        print(f"Error during analysis: {e}")
        raise


if __name__ == "__main__":
    main()
from collections import defaultdict
from pathlib import Path
from datetime import datetime


def parse_iso8601(timestamp_str):
    """Parse ISO8601 timestamp."""
    try:
        return datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
    except:
        return None


def analyze_log(log_path):
    """Analyze a pipeline log file."""
    if not Path(log_path).exists():
        print(f"Error: Log file not found: {log_path}")
        return None
    
    stats = {
        'total_steps': 0,
        'by_status': defaultdict(int),
        'by_step_name': defaultdict(int),
        'errors': [],
        'start_time': None,
        'end_time': None,
        'duration_seconds': None
    }
    
    print(f"Analyzing log: {log_path}")
    print("=" * 60)
    
    with open(log_path, 'r') as f:
        for line in f:
            try:
                entry = json.loads(line)
                
                stats['total_steps'] += 1
                stats['by_status'][entry['status']] += 1
                stats['by_step_name'][entry['step_name']] += 1
                
                # Track errors
                if entry['status'] == 'failed':
                    stats['errors'].append({
                        'step_id': entry['step_id'],
                        'step_name': entry['step_name'],
                        'error': entry.get('error', 'Unknown error'),
                        'timestamp': entry['timestamp']
                    })
                
                # Track timing
                timestamp = parse_iso8601(entry['timestamp'])
                if timestamp:
                    if stats['start_time'] is None or timestamp < stats['start_time']:
                        stats['start_time'] = timestamp
                    if stats['end_time'] is None or timestamp > stats['end_time']:
                        stats['end_time'] = timestamp
                
            except json.JSONDecodeError:
                print(f"Warning: Invalid JSON line: {line[:50]}...")
            except Exception as e:
                print(f"Warning: Error parsing line: {e}")
    
    # Calculate duration
    if stats['start_time'] and stats['end_time']:
        duration = stats['end_time'] - stats['start_time']
        stats['duration_seconds'] = duration.total_seconds()
    
    return stats


def print_summary(stats):
    """Print analysis summary."""
    print(f"\nTotal Steps: {stats['total_steps']}")
    
    print("\nBy Status:")
    for status, count in sorted(stats['by_status'].items()):
        print(f"  {status:12} {count:>5}")
    
    print("\nBy Step Name:")
    for step_name, count in sorted(stats['by_step_name'].items(), key=lambda x: -x[1]):
        print(f"  {step_name:30} {count:>5}")
    
    if stats['start_time']:
        print(f"\nStart Time: {stats['start_time'].isoformat()}")
    if stats['end_time']:
        print(f"End Time:   {stats['end_time'].isoformat()}")
    if stats['duration_seconds'] is not None:
        print(f"Duration:   {stats['duration_seconds']:.2f} seconds")
    
    if stats['errors']:
        print(f"\nErrors ({len(stats['errors'])}):")
        for error in stats['errors']:
            print(f"  Step {error['step_id']} ({error['step_name']}): {error['error']}")
    else:
        print("\n✓ No errors found")
    
    print("\n" + "=" * 60)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        # Default to example log
        log_file = "logs/indexing_pipeline.jsonl"
        print(f"No log file specified. Using default: {log_file}")
    else:
        log_file = sys.argv[1]
    
    stats = analyze_log(log_file)
    
    if stats:
        print_summary(stats)
        return 0
    else:
        return 1


if __name__ == "__main__":
    sys.exit(main())
