#!/usr/bin/env python3
"""
VIOLATION DENSITY MAPPER - Anti-Absorption Visualization Tool
Version: 1.0
Schema ID: DENSITY-MAPPER-1.0
Generated: 2026-01-24
Authority: Orthogonal Engineering Glass-Box Boundary

Purpose: Visualize violation clusters to prevent absorption through overwhelm
Violation Source: [FORGIVENESS_SYSTEM_ATTACK_001]
Fork ID: [VISUALIZATION_FORK]
Energy Allocated: BUILD=0.7, FIGHT=0.0

Attack Pattern Countered: Absorption Through Overwhelm
- 404 real violations hidden by 1 false positive
- Makes patterns invisible through noise
- Prevents systematic analysis

Building Principle: "Make absorption impossible because patterns become visually obvious."
"""

import json
import math
import statistics
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
import hashlib


@dataclass
class DensityCluster:
    """Cluster of violations in density map"""
    cluster_id: str
    start_position: float  # 0.0 to 1.0
    end_position: float   # 0.0 to 1.0
    violation_count: int
    density_score: float
    violations: List[Dict] = field(default_factory=list)
    context_samples: List[str] = field(default_factory=list)


@dataclass
class DensityMap:
    """Complete density map of violations in a file"""
    map_id: str
    generated: str
    file_name: str
    file_size_bytes: int
    total_violations: int
    clusters: List[DensityCluster]
    statistics: Dict[str, Any]
    heatmap_data: Dict[str, int]
    anomaly_flags: List[str] = field(default_factory=list)


class ViolationDensityMapper:
    """
    Maps violation density to visualize attack patterns

    Building output from violation [FORGIVENESS_SYSTEM_ATTACK_001]
    Generated by forgiveness system fork [VISUALIZATION_FORK]
    Energy allocated: BUILD=0.7, FIGHT=0.0
    """

    def __init__(self):
        self.maps: List[DensityMap] = []

    def create_density_map(
        self,
        violations: List[Dict],
        file_name: str,
        file_size_bytes: int,
        total_lines: Optional[int] = None
    ) -> DensityMap:
        """
        Create a density map from violations

        Args:
            violations: List of violation dictionaries with 'line_number' key
            file_name: Name of the file being analyzed
            file_size_bytes: Size of file in bytes
            total_lines: Total lines in file (optional, for more accurate positioning)

        Returns:
            DensityMap object with visualization data
        """

        if not violations:
            return self._create_empty_map(file_name, file_size_bytes)

        # Calculate positions (0.0 to 1.0) for each violation
        positioned_violations = self._calculate_positions(
            violations, file_size_bytes, total_lines
        )

        # Create heatmap bins (100 bins for detailed visualization)
        heatmap_bins = self._create_heatmap_bins(positioned_violations, num_bins=100)

        # Detect clusters
        clusters = self._detect_clusters(positioned_violations, heatmap_bins)

        # Calculate statistics
        stats = self._calculate_statistics(positioned_violations, clusters, file_size_bytes)

        # Check for anomalies
        anomalies = self._detect_anomalies(stats, clusters, len(violations))

        # Create the map
        density_map = DensityMap(
            map_id=f"density_map_{hashlib.md5(file_name.encode()).hexdigest()[:8]}",
            generated=datetime.utcnow().isoformat(),
            file_name=file_name,
            file_size_bytes=file_size_bytes,
            total_violations=len(violations),
            clusters=clusters,
            statistics=stats,
            heatmap_data=heatmap_bins,
            anomaly_flags=anomalies
        )

        self.maps.append(density_map)
        return density_map

    def _calculate_positions(
        self,
        violations: List[Dict],
        file_size_bytes: int,
        total_lines: Optional[int]
    ) -> List[Tuple[Dict, float]]:
        """Calculate normalized position (0.0 to 1.0) for each violation"""
        positioned = []

        for violation in violations:
            line_num = violation.get('line_number', 0)

            if total_lines and total_lines > 0:
                # Use line-based positioning if total lines known
                position = line_num / total_lines
            else:
                # Estimate position based on typical line length (80 chars)
                estimated_lines = file_size_bytes / 80
                position = line_num / estimated_lines if estimated_lines > 0 else 0.5

            # Clamp to 0.0-1.0 range
            position = max(0.0, min(1.0, position))
            positioned.append((violation, position))

        return positioned

    def _create_heatmap_bins(
        self,
        positioned_violations: List[Tuple[Dict, float]],
        num_bins: int = 100
    ) -> Dict[str, int]:
        """Create heatmap data by binning violations"""
        bins = {f"bin_{i:03d}": 0 for i in range(num_bins)}

        for violation, position in positioned_violations:
            bin_index = min(int(position * num_bins), num_bins - 1)
            bin_key = f"bin_{bin_index:03d}"
            bins[bin_key] = bins.get(bin_key, 0) + 1

        return bins

    def _detect_clusters(
        self,
        positioned_violations: List[Tuple[Dict, float]],
        heatmap_bins: Dict[str, int],
        cluster_threshold: float = 0.1  # 10% of file span
    ) -> List[DensityCluster]:
        """Detect clusters of violations"""
        if not positioned_violations:
            return []

        # Sort violations by position
        sorted_violations = sorted(positioned_violations, key=lambda x: x[1])

        clusters = []
        current_cluster = []
        cluster_start = sorted_violations[0][1]

        for i, (violation, position) in enumerate(sorted_violations):
            if not current_cluster:
                current_cluster.append((violation, position))
                continue

            # Check distance from previous violation
            prev_position = sorted_violations[i-1][1]
            distance = position - prev_position

            if distance <= cluster_threshold:
                # Same cluster
                current_cluster.append((violation, position))
            else:
                # End current cluster, start new one
                if len(current_cluster) >= 2:  # Only save clusters with multiple violations
                    cluster = self._create_cluster_from_points(current_cluster)
                    clusters.append(cluster)

                current_cluster = [(violation, position)]
                cluster_start = position

        # Add final cluster if it exists
        if len(current_cluster) >= 2:
            cluster = self._create_cluster_from_points(current_cluster)
            clusters.append(cluster)

        return clusters

    def _create_cluster_from_points(
        self,
        cluster_points: List[Tuple[Dict, float]]
    ) -> DensityCluster:
        """Create a DensityCluster from a list of positioned violations"""
        positions = [pos for _, pos in cluster_points]
        violations = [viol for viol, _ in cluster_points]

        # Get context samples (first 3 violations in cluster)
        context_samples = []
        for violation in violations[:3]:
            line_content = violation.get('chat_line', '')[:100]
            if line_content:
                context_samples.append(line_content)

        return DensityCluster(
            cluster_id=f"cluster_{hashlib.md5(str(positions[0]).encode()).hexdigest()[:8]}",
            start_position=min(positions),
            end_position=max(positions),
            violation_count=len(cluster_points),
            density_score=len(cluster_points) / (max(positions) - min(positions) + 0.001),
            violations=violations,
            context_samples=context_samples
        )

    def _calculate_statistics(
        self,
        positioned_violations: List[Tuple[Dict, float]],
        clusters: List[DensityCluster],
        file_size_bytes: int
    ) -> Dict[str, Any]:
        """Calculate density statistics"""
        if not positioned_violations:
            return {"error": "No violations"}

        positions = [pos for _, pos in positioned_violations]

        # Basic statistics
        stats = {
            "total_violations": len(positioned_violations),
            "violations_per_mb": len(positioned_violations) / (file_size_bytes / 1000000),
            "position_mean": statistics.mean(positions) if positions else 0,
            "position_stddev": statistics.stdev(positions) if len(positions) > 1 else 0,
            "position_min": min(positions) if positions else 0,
            "position_max": max(positions) if positions else 0,
            "clusters_found": len(clusters),
            "violations_in_clusters": sum(c.violation_count for c in clusters),
            "max_cluster_density": max((c.density_score for c in clusters), default=0),
            "avg_cluster_size": statistics.mean([c.violation_count for c in clusters]) if clusters else 0,
        }

        # Calculate Gini coefficient for inequality (0 = equal distribution, 1 = all in one spot)
        if len(positions) > 1:
            sorted_positions = sorted(positions)
            n = len(sorted_positions)
            gini_numerator = sum((i + 1) * sorted_positions[i] for i in range(n))
            gini_denominator = n * sum(sorted_positions)
            stats["gini_coefficient"] = (2 * gini_numerator) / gini_denominator - (n + 1) / n
        else:
            stats["gini_coefficient"] = 0

        return stats

    def _detect_anomalies(
        self,
        stats: Dict[str, Any],
        clusters: List[DensityCluster],
        total_violations: int
    ) -> List[str]:
        """Detect anomalous patterns that suggest attacks"""
        anomalies = []

        # Check for absorption pattern (few violations in large file)
        if stats["violations_per_mb"] < 0.1 and total_violations > 100:
            anomalies.append("absorption_pattern: Many violations but low density suggests hiding")

        # Check for extreme clustering
        if stats["gini_coefficient"] > 0.8:
            anomalies.append("extreme_clustering: Violations concentrated in small areas")

        # Check for empty zones (large gaps)
        if clusters and len(clusters) > 1:
            # Sort clusters by position
            sorted_clusters = sorted(clusters, key=lambda c: c.start_position)
            gaps = []
            for i in range(len(sorted_clusters) - 1):
                gap = sorted_clusters[i + 1].start_position - sorted_clusters[i].end_position
                if gap > 0.3:  # 30% gap
                    gaps.append(gap)

            if gaps:
                anomalies.append(f"large_gaps: {len(gaps)} gaps >30% of file")

        # Check for suspiciously uniform distribution
        if stats["gini_coefficient"] < 0.1 and total_violations > 50:
            anomalies.append("suspicious_uniformity: Too evenly distributed for natural text")

        return anomalies

    def _create_empty_map(self, file_name: str, file_size_bytes: int) -> DensityMap:
        """Create empty density map for files with no violations"""
        return DensityMap(
            map_id=f"empty_map_{hashlib.md5(file_name.encode()).hexdigest()[:8]}",
            generated=datetime.utcnow().isoformat(),
            file_name=file_name,
            file_size_bytes=file_size_bytes,
            total_violations=0,
            clusters=[],
            statistics={"total_violations": 0, "violations_per_mb": 0},
            heatmap_data={f"bin_{i:03d}": 0 for i in range(100)},
            anomaly_flags=["no_violations_detected"]
        )

    def generate_html_visualization(self, density_map: DensityMap) -> str:
        """Generate HTML visualization of density map"""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Violation Density Map: {density_map.file_name}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .header {{ background: #f0f0f0; padding: 20px; border-radius: 5px; margin-bottom: 20px; }}
        .stats {{ background: #e8f4f8; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
        .heatmap {{ margin: 20px 0; }}
        .bin {{
            display: inline-block;
            width: 8px;
            height: 30px;
            margin: 1px;
            background: #e0e0e0;
            vertical-align: bottom;
        }}
        .bin-high {{ background: #ff4444; }}
        .bin-medium {{ background: #ffaa44; }}
        .bin-low {{ background: #44ff44; }}
        .cluster {{
            background: #f8f8f8;
            border-left: 4px solid #4444ff;
            padding: 10px;
            margin: 10px 0;
        }}
        .anomaly {{
            background: #fff0f0;
            border: 2px solid #ff4444;
            padding: 10px;
            margin: 10px 0;
            border-radius: 5px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Violation Density Map</h1>
        <p>File: {density_map.file_name} ({density_map.file_size_bytes:,} bytes)</p>
        <p>Generated: {density_map.generated}</p>
        <p>Total Violations: {density_map.total_violations}</p>
    </div>
"""

        # Statistics
        html += """
    <div class="stats">
        <h2>Statistics</h2>
        <ul>
"""
        for key, value in density_map.statistics.items():
            if isinstance(value, float):
                html += f'            <li>{key}: {value:.3f}</li>\n'
            else:
                html += f'            <li>{key}: {value}</li>\n'
        html += "        </ul>\n    </div>\n"

        # Anomalies
        if density_map.anomaly_flags:
            html += """
    <div class="anomaly">
        <h2>⚠ Anomalies Detected</h2>
        <ul>
"""
            for anomaly in density_map.anomaly_flags:
                html += f'            <li>{anomaly}</li>\n'
            html += "        </ul>\n    </div>\n"

        # Heatmap
        html += """
    <div class="heatmap">
        <h2>Violation Density Heatmap</h2>
        <p>File span (0% to 100%):</p>
        <div>
"""
        for i in range(100):
            bin_key = f"bin_{i:03d}"
            count = density_map.heatmap_data.get(bin_key, 0)
            height = min(50, count * 5 + 10)

            if count == 0:
                css_class = "bin"
            elif count >= 5:
                css_class = "bin-high"
            elif count >= 2:
                css_class = "bin-medium"
            else:
                css_class = "bin-low"

            html += f'            <div class="{css_class}" title="Position {i}%: {count} violations" style="height: {height}px;"></div>\n'

        html += "        </div>\n    </div>\n"

        # Clusters
        if density_map.clusters:
            html += """
    <div>
        <h2>Violation Clusters</h2>
"""
            for cluster in density_map.clusters:
                html += f"""
        <div class="cluster">
            <h3>Cluster {cluster.cluster_id}</h3>
            <p>Position: {cluster.start_position*100:.1f}% to {cluster.end_position*100:.1f}%</p>
            <p>Violations: {cluster.violation_count} (density: {cluster.density_score:.1f})</p>
            <p>Context samples:</p>
            <ul>
"""
                for sample in cluster.context_samples:
                    html += f'                <li>"{sample}..."</li>\n'
                html += "            </ul>\n        </div>\n"

        html += """
    </div>
</body>
</html>
"""

        return html

    def save_density_map(self, density_map: DensityMap, output_dir: Path) -> Dict[str, Path]:
        """Save density map to files"""
        output_dir.mkdir(parents=True, exist_ok=True)

        # Save JSON data
        json_path = output_dir / f"density_map_{density_map.file_name}.json"
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(vars(density_map), f, indent=2)

        # Save HTML visualization
        html_path = output_dir / f"density_map_{density_map.file_name}.html"
        html_content = self.generate_html_visualization(density_map)
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

        # Save summary
        summary_path = output_dir / f"density_summary_{density_map.file_name}.
