"""
Phase 9 Trace Generator

Generates enriched trace documents for Phase 9 with advanced causal analysis,
methodological scoring, and cryptographic linkage to Phase 8.

Author: Orthogonal Engineering System
Date: 2026-01-22
Version: 1.0.0
"""

import argparse
import hashlib
import json
import sys
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

# Add toolkit to path
sys.path.insert(0, str(Path(__file__).parent.parent / "toolkit"))

from toolkit.oe.advanced_evidence import AdvancedEvidenceStore, EvidenceConfidence
from toolkit.oe.causal_analyzer import CausalAnalyzer
from toolkit.oe.evidence_store import EvidenceStore
from toolkit.oe.trace_enricher import TraceEnricher, TraceEnrichmentLevel


class Phase9TraceGenerator:
    """
    Generator for Phase 9 enriched trace documents.

    Features:
    1. Generates trace documents compliant with Phase 9 JSON schema
    2. Enriches traces with advanced causal analysis
    3. Includes methodological invariant compliance scores
    4. Creates cryptographic linkage to Phase 8 artifacts
    5. Validates trace against Phase 9 schema
    6. Signs trace with SHA256 hash
    """

    def __init__(self, evidence_store_path: Optional[str] = None):
        """
        Initialize trace generator.

        Args:
            evidence_store_path: Path to evidence store (default: logs/evidence)
        """
        self.evidence_store_path = evidence_store_path or "logs/evidence"
        self.evidence_store = AdvancedEvidenceStore(base_path=self.evidence_store_path)
        self.causal_analyzer = CausalAnalyzer(self.evidence_store)
        self.trace_enricher = TraceEnricher(self.evidence_store)

        # Create trace output directory
        self.trace_output_path = Path("logs/traces/phase9")
        self.trace_output_path.mkdir(parents=True, exist_ok=True)

    def generate_base_trace(self) -> Dict[str, Any]:
        """
        Generate base trace document with required fields.

        Returns:
            Base trace document dictionary
        """
        # Get repository information
        repo_meta = self._get_repository_metadata()

        # Get environment snapshot
        env_snapshot = self._get_environment_snapshot()

        # Scan for artifacts
        artifact_scan = self._scan_artifacts()

        # Generate trace ID
        trace_id = f"GB-TRACE-{uuid.uuid4().hex[:8].upper()}-{uuid.uuid4().hex[:4].upper()}-{uuid.uuid4().hex[:4].upper()}-{uuid.uuid4().hex[:4].upper()}-{uuid.uuid4().hex[:12].upper()}"

        base_trace = {
            "trace_id": trace_id,
            "timestamp": datetime.now().isoformat(),
            "repository_meta": repo_meta,
            "environment_snapshot": env_snapshot,
            "artifact_scan": artifact_scan,
            "boundary_violations": [],
            "suppressed_signals": [],
            "timeline_sequence": {
                "events": [],
                "violations": [],
                "sequence_valid": True,
            },
            "hash_manifest": {
                "algorithm": "SHA256",
                "files_hashed": 0,
                "root_hash": "",
                "file_hashes": {},
            },
            "signature": {
                "signed_by": "Phase9TraceGenerator",
                "signature_hash": "",
                "verification_key": "phase9-trace-generator-v1.0.0",
                "timestamp": datetime.now().isoformat(),
                "note": "Trace generated by Phase 9 Trace Generator",
            },
            "python_enforcer_active": True,
            "ide_integration": {
                "autofix_enabled": True,
                "structural_consistency": True,
                "boundary_awareness": True,
                "doc_sync": True,
                "phase9_dsl_support": True,
            },
            "phase9_metadata": {
                "phase": 9,
                "schema_version": "1.12",
                "generated_by": "Phase9TraceGenerator",
                "generation_timestamp": datetime.now().isoformat(),
            },
        }

        # Add timeline events
        base_trace["timeline_sequence"]["events"] = self._generate_timeline_events(
            base_trace
        )

        # Calculate hash manifest
        base_trace["hash_manifest"] = self._calculate_hash_manifest(base_trace)

        # Sign the trace
        base_trace["signature"]["signature_hash"] = self._sign_trace(base_trace)

        return base_trace

    def _get_repository_metadata(self) -> Dict[str, Any]:
        """
        Get repository metadata.

        Returns:
            Repository metadata dictionary
        """
        try:
            # Try to get git information
            import subprocess

            repo_name = "orthogonal-engineering"

            # Get commit hash
            try:
                commit_hash = subprocess.check_output(
                    ["git", "rev-parse", "HEAD"],
                    cwd=Path(__file__).parent.parent,
                    text=True,
                ).strip()
            except:
                commit_hash = "unknown"

            # Get branch name
            try:
                branch = subprocess.check_output(
                    ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                    cwd=Path(__file__).parent.parent,
                    text=True,
                ).strip()
            except:
                branch = "unknown"

            # Check if repository is dirty
            try:
                status = subprocess.check_output(
                    ["git", "status", "--porcelain"],
                    cwd=Path(__file__).parent.parent,
                    text=True,
                ).strip()
                dirty = len(status) > 0
            except:
                dirty = False

            return {
                "name": repo_name,
                "version": "1.0.0",
                "commit_hash": commit_hash,
                "branch": branch,
                "dirty": dirty,
            }

        except Exception:
            # Fallback if git is not available
            return {
                "name": "orthogonal-engineering",
                "version": "1.0.0",
                "commit_hash": "unknown",
                "branch": "unknown",
                "dirty": False,
            }

    def _get_environment_snapshot(self) -> Dict[str, Any]:
        """
        Get environment snapshot.

        Returns:
            Environment snapshot dictionary
        """
        import platform
        import sys

        # Get Python dependencies
        dependencies = []
        try:
            import pkg_resources

            for dist in pkg_resources.working_set:
                dependencies.append(f"{dist.key}=={dist.version}")
        except:
            # Fallback if pkg_resources is not available
            dependencies = ["unknown"]

        return {
            "python_version": sys.version,
            "dependencies": dependencies,
            "system_info": {
                "platform": platform.platform(),
                "architecture": platform.machine(),
                "cwd": str(Path.cwd()),
                "python_executable": sys.executable,
            },
        }

    def _scan_artifacts(self) -> Dict[str, Any]:
        """
        Scan for required Phase 9 artifacts.

        Returns:
            Artifact scan results dictionary
        """
        required_artifacts = [
            # Toolkit modules
            "toolkit/oe/advanced_evidence.py",
            "toolkit/oe/causal_analyzer.py",
            "toolkit/oe/workflow_dsl.py",
            "toolkit/oe/trace_enricher.py",
            "toolkit/oe/debt_calculator.py",
            # Test files
            "toolkit/tests/test_advanced_evidence.py",
            "toolkit/tests/test_causal_analyzer.py",
            "toolkit/tests/test_workflow_dsl.py",
            "toolkit/tests/test_trace_enricher.py",
            "toolkit/tests/test_debt_calculator.py",
            # Workflow files
            "workflows/phase9_advanced_validation.yaml",
            "workflows/causal_analysis_workflow.yaml",
            "workflows/debt_tracking_workflow.yaml",
            "workflows/trace_enrichment_workflow.yaml",
            # Automation scripts
            "automation/phase9_workflow_executor.py",
            "automation/validate_phase9_artifacts.py",
            "automation/generate_phase9_trace.py",
            "automation/phase9_causal_analysis.py",
            # Documentation
            "documentation/PHASE_9_METHODOLOGICAL_EXPANSION.md",
            "documentation/PHASE_9_WORKFLOW_DSL_SPECIFICATION.md",
            "documentation/PHASE_9_EVIDENCE_STORE_ENHANCEMENTS.md",
            "documentation/PHASE_9_TRACE_ENRICHMENT_SPEC.md",
        ]

        found_artifacts = []
        missing_artifacts = []

        for artifact_path in required_artifacts:
            path = Path(artifact_path)
            if path.exists():
                found_artifacts.append(artifact_path)
            else:
                missing_artifacts.append(artifact_path)

        return {
            "required_artifacts": required_artifacts,
            "found_artifacts": found_artifacts,
            "missing_artifacts": missing_artifacts,
            "scan_status": "complete" if len(missing_artifacts) == 0 else "partial",
        }

    def _generate_timeline_events(self, trace: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Generate timeline events for trace.

        Args:
            trace: Trace document

        Returns:
            List of timeline events
        """
        events = []

        # Environment snapshot event
        events.append(
            {
                "event_type": "environment_snapshot",
                "timestamp": trace["timestamp"],
                "component": "Phase9TraceGenerator",
                "details": {
                    "python_version": trace["environment_snapshot"]["python_version"],
                    "dependencies_count": len(
                        trace["environment_snapshot"]["dependencies"]
                    ),
                },
            }
        )

        # Artifact scan event
        events.append(
            {
                "event_type": "artifact_scan",
                "timestamp": datetime.now().isoformat(),
                "component": "Phase9TraceGenerator",
                "details": {
                    "required_count": len(trace["artifact_scan"]["required_artifacts"]),
                    "found_count": len(trace["artifact_scan"]["found_artifacts"]),
                    "missing_count": len(trace["artifact_scan"]["missing_artifacts"]),
                },
            }
        )

        # Boundary validation event
        events.append(
            {
                "event_type": "boundary_validation",
                "timestamp": datetime.now().isoformat(),
                "component": "Phase9TraceGenerator",
                "details": {
                    "violations_count": len(trace["boundary_violations"]),
                    "suppressed_signals_count": len(trace["suppressed_signals"]),
                },
            }
        )

        # Phase 9 analysis event
        events.append(
            {
                "event_type": "phase9_analysis",
                "timestamp": datetime.now().isoformat(),
                "component": "Phase9TraceGenerator",
                "details": {
                    "phase": trace["phase9_metadata"]["phase"],
                    "schema_version": trace["phase9_metadata"]["schema_version"],
                },
            }
        )

        # Causal inference event (if evidence exists)
        if self.evidence_store.causal_graph:
            events.append(
                {
                    "event_type": "causal_inference",
                    "timestamp": datetime.now().isoformat(),
                    "component": "Phase9TraceGenerator",
                    "details": {
                        "causal_nodes": len(self.evidence_store.causal_graph),
                        "causal_edges": len(self.evidence_store.causal_edges),
                        "evidence_chains": len(self.evidence_store.evidence_chains),
                    },
                }
            )

        return events

    def _calculate_hash_manifest(self, trace: Dict[str, Any]) -> Dict[str, Any]:
        """
        Calculate hash manifest for trace artifacts.

        Args:
            trace: Trace document

        Returns:
            Hash manifest dictionary
        """
        file_hashes = {}
        files_hashed = 0

        # Hash found artifacts
        for artifact_path in trace["artifact_scan"]["found_artifacts"]:
            path = Path(artifact_path)
            if path.exists() and path.is_file():
                try:
                    file_hash = hashlib.sha256(path.read_bytes()).hexdigest()
                    file_hashes[artifact_path] = file_hash
                    files_hashed += 1
                except Exception:
                    # Skip files that can't be read
                    continue

        # Calculate root hash
        if file_hashes:
            # Sort by filename for deterministic hashing
            sorted_hashes = sorted(file_hashes.items())
            hash_string = json.dumps(sorted_hashes, sort_keys=True)
            root_hash = hashlib.sha256(hash_string.encode()).hexdigest()
        else:
            root_hash = ""

        return {
            "algorithm": "SHA256",
            "files_hashed": files_hashed,
            "root_hash": root_hash,
            "file_hashes": file_hashes,
        }

    def _sign_trace(self, trace: Dict[str, Any]) -> str:
        """
        Sign trace document with SHA256 hash.

        Args:
            trace: Trace document to sign

        Returns:
            Signature hash
        """
        # Create a copy without the signature field for hashing
        trace_copy = trace.copy()
        trace_copy["signature"] = {"signature_hash": ""}

        # Convert to JSON string with sorted keys for deterministic hashing
        trace_json = json.dumps(trace_copy, sort_keys=True)

        # Calculate SHA256 hash
        return hashlib.sha256(trace_json.encode()).hexdigest()

    def generate_enriched_trace(
        self, enrichment_level: TraceEnrichmentLevel = TraceEnrichmentLevel.COMPLETE
    ) -> Dict[str, Any]:
        """
        Generate enriched trace document.

        Args:
            enrichment_level: Level of enrichment to apply

        Returns:
            Enriched trace document
        """
        print("Generating base trace...")
        base_trace = self.generate_base_trace()

        print(f"Enriching trace at level: {enrichment_level.value}...")
        enriched_trace = self.trace_enricher.enrich_trace(base_trace, enrichment_level)

        # Add cryptographic linkage to Phase 8
        enriched_trace = self._add_phase8_linkage(enriched_trace)

        # Validate enriched trace
        validation_result = self._validate_trace(enriched_trace)
        enriched_trace["validation_result"] = validation_result

        return enriched_trace

    def _add_phase8_linkage(self, trace: Dict[str, Any]) -> Dict[str, Any]:
        """
        Add cryptographic linkage to Phase 8 artifacts.

        Args:
            trace: Trace document to enhance

        Returns:
            Enhanced trace with Phase 8 linkage
        """
        phase8_linkage = {
            "phase8_commit_hash": "62bead3",  # From Phase 10 blueprint
            "linked_artifacts": [],
            "verification_status": "pending",
            "linkage_timestamp": datetime.now().isoformat(),
        }

        # Try to verify Phase 8 artifacts
        try:
            # Check for Phase 8 artifacts
            phase8_artifacts = [
                "automation/phase8_atomic_workflow.py",
                "automation/run_full_audit_with_trace.py",
                "documentation/GLASS_BOX_BOUNDARY_v1.11.html",
            ]

            verified_artifacts = []
            for artifact in phase8_artifacts:
                path = Path(artifact)
                if path.exists():
                    verified_artifacts.append(
                        {
                            "artifact": artifact,
                            "exists": True,
                            "hash": hashlib.sha256(path.read_bytes()).hexdigest()
                            if path.is_file()
                            else "directory",
                        }
                    )
                else:
                    verified_artifacts.append(
                        {"artifact": artifact, "exists": False, "hash": "missing"}
                    )

            phase8_linkage["linked_artifacts"] = verified_artifacts

            # Determine verification status
            all_exist = all(artifact["exists"] for artifact in verified_artifacts)
            phase8_linkage["verification_status"] = (
                "verified" if all_exist else "partial"
            )

        except Exception as e:
            phase8_linkage["verification_status"] = f"error: {str(e)}"

        # Add to trace
        if "phase9_metadata" not in trace:
            trace["phase9_metadata"] = {}

        trace["phase9_metadata"]["phase8_linkage"] = phase8_linkage

        return trace

    def _validate_trace(self, trace: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate trace against Phase 9 schema requirements.

        Args:
            trace: Trace document to validate

        Returns:
            Validation results dictionary
        """
        validation_results = {
            "valid": True,
            "errors": [],
            "warnings": [],
            "timestamp": datetime.now().isoformat(),
        }

        # Check required fields from Phase 9 schema
        required_fields = [
            "trace_id",
            "timestamp",
            "repository_meta",
            "environment_snapshot",
            "artifact_scan",
            "boundary_violations",
            "suppressed_signals",
            "timeline_sequence",
            "hash_manifest",
            "signature",
            "python_enforcer_active",
            "ide_integration",
            "phase9_metadata",
            "causal_graph",
            "methodological_scores",
        ]

        for field in required_fields:
            if field not in trace:
                validation_results["valid"] = False
                validation_results["errors"].append(f"Missing required field: {field}")

        # Check trace_id format
        if "trace_id" in trace:
            import re

            pattern = r"^GB-TRACE-[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$"
