"""tools/kimi_cli_restoration_spec.py -- Generate Kimi CLI instructions from campaign spec.

Part 5E of Forensic Offensive Campaign.

Automates what Devin has been doing manually: reads a campaign spec JSON
and generates structured Kimi CLI instructions.
"""

from __future__ import annotations

import json
import sys
from fractions import Fraction
from pathlib import Path
from typing import Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from axioms.logic import ProofObject


def generate_restoration_spec(spec_path: Path) -> Tuple[bool, ProofObject]:
    """Generate Kimi CLI restoration instructions from a campaign spec.

    Standard: RESTORE-001 spec generation.
    Falsifies if: spec exists but generated instructions are empty.
    falsifies_if: spec exists but generated instructions are empty.
    """
    if not spec_path.exists():
        return False, ProofObject(
            rule="kimi_restoration_spec",
            premises=[f"spec_path={spec_path}"],
            conclusion="FAIL: Campaign spec file not found",
        )

    try:
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return False, ProofObject(
            rule="kimi_restoration_spec",
            premises=[f"spec_path={spec_path}"],
            conclusion=f"FAIL: Could not parse spec: {exc}",
        )

    campaign = spec.get("campaign", "UNKNOWN")
    expected = spec.get("expected_outputs", [])

    instructions = [
        f"# Kimi CLI Restoration Instructions",
        f"# Campaign: {campaign}",
        f"# Generated by: tools/kimi_cli_restoration_spec.py",
        "",
        f"## Deliverables ({len(expected)} items)",
        "",
    ]
    for item in expected:
        path = item.get("path", "unknown")
        item_type = item.get("type", "file")
        instructions.append(f"- [{item_type.upper()}] `{path}`")

    instructions.append("")
    instructions.append("## Constraints")
    instructions.append("- 0 floats")
    instructions.append("- 0 stubs")
    instructions.append("- Every function returns Tuple[bool, ProofObject]")
    instructions.append("- Every docstring has falsifies_if")
    instructions.append("- Commit after each phase")

    output_path = spec_path.with_suffix(". restoration.md")
    output_path.write_text("\n".join(instructions), encoding="utf-8")

    proof = ProofObject(
        rule="kimi_restoration_spec",
        premises=[
            f"campaign={campaign}",
            f"deliverables={len(expected)}",
        ],
        conclusion=f"PASS: Generated restoration spec with {len(expected)} deliverable(s)",
    )
    return True, proof


def main() -> int:
    """CLI entry point.

    falsifies_if: exit code 0 when no spec path is provided.
    """
    if len(sys.argv) < 2:
        print("Usage: python tools/kimi_cli_restoration_spec.py <campaign_spec.json>")
        return 1
    spec_path = Path(sys.argv[1])
    ok, proof = generate_restoration_spec(spec_path)
    print(proof.conclusion)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
